# Generated by Django 3.2.9 on 2021-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя пользователя')),
                ('nick', models.CharField(max_length=64, unique=True, verbose_name='ник пользователя')),
            ],
        ),
    ]
